-- ============================================================
--  Workforce & Billing Management SaaS — Full Database Schema
-- ============================================================
-- Conventions:
--   • All PKs are UUIDs, generated by default
--   • created_at / updated_at on every table
--   • Soft deletes via deleted_at (nullable) on key tables
--   • All FKs have explicit ON DELETE behaviour noted
-- ============================================================


-- ------------------------------------------------------------
-- EXTENSIONS
-- ------------------------------------------------------------

CREATE EXTENSION IF NOT EXISTS "pgcrypto";   -- gen_random_uuid()
CREATE EXTENSION IF NOT EXISTS "citext";     -- case-insensitive email


-- ============================================================
-- 1. PLANS & ENTITLEMENTS
-- ============================================================

CREATE TABLE plans (
    plan_id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name                     VARCHAR(100)    NOT NULL,           -- e.g. "Starter", "Pro", "Business"
    max_workers              INT             NOT NULL,           -- worker seat cap (-1 = unlimited)
    modules                  JSONB           NOT NULL DEFAULT '[]', -- e.g. ["expenses","bio_page","upcoming_bills"]
    history_months           INT             NOT NULL DEFAULT 12,   -- how far back the org can query
    stripe_price_id_monthly  VARCHAR(100),
    stripe_price_id_yearly   VARCHAR(100),
    tap_plan_id              VARCHAR(100),
    apple_product_id_monthly VARCHAR(100),
    apple_product_id_yearly  VARCHAR(100),
    is_active                BOOLEAN         NOT NULL DEFAULT TRUE, -- hide retired plans from signup
    created_at               TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    updated_at               TIMESTAMPTZ     NOT NULL DEFAULT NOW()
);

COMMENT ON COLUMN plans.max_workers   IS '-1 means unlimited workers';
COMMENT ON COLUMN plans.modules       IS 'JSON array of module keys available on this plan';
COMMENT ON COLUMN plans.history_months IS 'How many months of historical data the org can access';


-- ============================================================
-- 2. USERS & AUTH
-- ============================================================

CREATE TABLE users (
    id                UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    email             CITEXT      NOT NULL UNIQUE,
    password_hash     TEXT        NOT NULL,
    otp_verified      BOOLEAN     NOT NULL DEFAULT FALSE,
    otp_code          VARCHAR(10),                          -- cleared after verification
    otp_expires_at    TIMESTAMPTZ,
    full_name         VARCHAR(200),
    created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at        TIMESTAMPTZ                           -- soft delete; requires email+password re-confirm
);

COMMENT ON COLUMN users.deleted_at IS 'Set on account deletion after user re-confirms email+password';


-- ============================================================
-- 3. ORGANIZATIONS
-- ============================================================

CREATE TABLE organizations (
    id                UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    owner_user_id     UUID        NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    plan_id           UUID        NOT NULL REFERENCES plans(plan_id) ON DELETE RESTRICT,
    name              VARCHAR(200) NOT NULL,
    organization_type VARCHAR(50) NOT NULL,  -- construction | gym | tutoring | contractor | sales | cleaning | …
    logo_filename     VARCHAR(255),          -- relative filename only; CDN base URL prefixed in code
    created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at        TIMESTAMPTZ
);

COMMENT ON COLUMN organizations.organization_type IS 'Drives localized label keys throughout the UI (e.g. gym → "Coach", construction → "Worker")';
COMMENT ON COLUMN organizations.logo_filename     IS 'Relative filename only — never a full URL. Served via cdn.mydomain.com/imgs/';


-- ============================================================
-- 4. SUBSCRIPTIONS / ENTITLEMENTS
-- ============================================================
-- Source of truth for feature gating. NEVER call Stripe/Tap/Apple
-- at request time — read only this table.

CREATE TABLE subscribed_services (
    id                       UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    organization_id          UUID        NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    plan_id                  UUID        NOT NULL REFERENCES plans(plan_id) ON DELETE RESTRICT,
    payment_provider         VARCHAR(20) NOT NULL CHECK (payment_provider IN ('stripe','tap','apple')),
    external_subscription_id VARCHAR(255) NOT NULL,  -- Stripe sub ID / Apple orig. transaction ID / Tap sub ID
    billing_cadence          VARCHAR(10) NOT NULL CHECK (billing_cadence IN ('monthly','yearly')),
    since                    DATE        NOT NULL,
    active_until             DATE        NOT NULL,   -- end of current paid period
    price                    DECIMAL(10,2) NOT NULL, -- amount charged per cycle
    is_cancelled             BOOLEAN     NOT NULL DEFAULT FALSE, -- stops renewal; stays active until active_until
    is_active                BOOLEAN     NOT NULL DEFAULT TRUE,  -- THE ONLY FIELD rest of app checks
    updated_at               TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_at               TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON COLUMN subscribed_services.is_active             IS 'THE only field the app checks for feature gating. Updated by webhook handlers, never live-queried from payment providers.';
COMMENT ON COLUMN subscribed_services.external_subscription_id IS 'Used by incoming webhooks to find the right row';
COMMENT ON COLUMN subscribed_services.is_cancelled          IS 'TRUE = do not renew, but keep is_active=TRUE until active_until passes';


-- ============================================================
-- 5. ASSETS
-- ============================================================
-- Stores relative filenames only. CDN base URL is code-level config.

CREATE TABLE assets (
    id           UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    owner_type   VARCHAR(50) NOT NULL,   -- 'organization' | 'worker' | 'bio_page' | 'upcoming_bill'
    owner_id     UUID        NOT NULL,
    filename     VARCHAR(255) NOT NULL,  -- e.g. "worker_abc123_id.png" — relative path only
    mime_type    VARCHAR(100),
    uploaded_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON COLUMN assets.filename  IS 'Relative path only. Prefixed with cdn.mydomain.com/imgs/ at render time.';
COMMENT ON COLUMN assets.owner_type IS 'Polymorphic: organization | worker | bio_page | upcoming_bill';


-- ============================================================
-- 6. WORKERS
-- ============================================================

CREATE TABLE workers (
    id               UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    organization_id  UUID        NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    name             VARCHAR(200) NOT NULL,
    profile_image_id UUID        REFERENCES assets(id) ON DELETE SET NULL,
    id_document_id   UUID        REFERENCES assets(id) ON DELETE SET NULL,  -- optional ID/passport/license
    pay_type         VARCHAR(10) NOT NULL CHECK (pay_type IN ('monthly','hourly')),
    monthly_amount   DECIMAL(10,2),   -- used when pay_type = 'monthly'
    hourly_rate      DECIMAL(10,2),   -- used when pay_type = 'hourly'
    created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at       TIMESTAMPTZ,     -- soft delete

    CONSTRAINT chk_pay_type_fields CHECK (
        (pay_type = 'monthly' AND monthly_amount IS NOT NULL) OR
        (pay_type = 'hourly'  AND hourly_rate    IS NOT NULL)
    )
);

COMMENT ON COLUMN workers.pay_type       IS 'monthly = fixed salary; hourly = rate × hours logged';
COMMENT ON COLUMN workers.monthly_amount IS 'Fixed monthly salary. hours_logged still tracked for analytics.';
COMMENT ON COLUMN workers.hourly_rate    IS 'Per-hour rate. amount_owed = hours × rate.';


-- ============================================================
-- 7. CLIENTS
-- ============================================================

CREATE TABLE clients (
    id               UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    organization_id  UUID        NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    name             VARCHAR(200) NOT NULL,
    email            CITEXT,
    phone            VARCHAR(50),
    notes            TEXT,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at       TIMESTAMPTZ
);


-- Client feedback / ratings (post-job)
CREATE TABLE client_feedback (
    id          UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    client_id   UUID        NOT NULL REFERENCES clients(id) ON DELETE CASCADE,
    job_id      UUID        NOT NULL,   -- FK added after jobs table below
    rating      SMALLINT    CHECK (rating BETWEEN 1 AND 5),
    comment     TEXT,
    submitted_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


-- ============================================================
-- 8. JOB TEMPLATES (built-in, not user-created in v1)
-- ============================================================

CREATE TABLE job_templates (
    id          UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    name        VARCHAR(200) NOT NULL,
    description TEXT,
    industry    VARCHAR(50),   -- optional: ties a template to a vertical (null = universal)
    is_active   BOOLEAN     NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON COLUMN job_templates.industry IS 'NULL = available to all verticals. Set to restrict template to a specific org type.';


-- ============================================================
-- 9. JOBS
-- ============================================================

CREATE TABLE jobs (
    id               UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    organization_id  UUID        NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    client_id        UUID        REFERENCES clients(id) ON DELETE SET NULL,
    template_id      UUID        REFERENCES job_templates(id) ON DELETE SET NULL,
    title            VARCHAR(200) NOT NULL,
    status           VARCHAR(20) NOT NULL DEFAULT 'pending'
                         CHECK (status IN ('pending','in_progress','done')),
    created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at       TIMESTAMPTZ
);

-- Add the deferred FK on client_feedback now that jobs exists
ALTER TABLE client_feedback
    ADD CONSTRAINT fk_feedback_job FOREIGN KEY (job_id)
    REFERENCES jobs(id) ON DELETE CASCADE;


-- ============================================================
-- 10. JOB DAYS
-- ============================================================

CREATE TABLE job_days (
    id       UUID    PRIMARY KEY DEFAULT gen_random_uuid(),
    job_id   UUID    NOT NULL REFERENCES jobs(id) ON DELETE CASCADE,
    date     DATE    NOT NULL,
    invoiced BOOLEAN NOT NULL DEFAULT FALSE,  -- blocks/flags edits once invoice generated
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    UNIQUE (job_id, date)   -- one row per job per calendar day
);

COMMENT ON COLUMN job_days.invoiced IS 'TRUE once an invoice covers this date. Further edits are blocked or flagged.';


-- ============================================================
-- 11. DAY ASSIGNMENTS
-- ============================================================

CREATE TABLE day_assignments (
    id          UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
    job_day_id  UUID         NOT NULL REFERENCES job_days(id) ON DELETE CASCADE,
    worker_id   UUID         NOT NULL REFERENCES workers(id) ON DELETE RESTRICT,
    hours       DECIMAL(5,2) NOT NULL CHECK (hours >= 0),
    -- Audit trail for retroactive edits
    edited_at   TIMESTAMPTZ,
    edited_by   UUID         REFERENCES users(id) ON DELETE SET NULL,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),

    UNIQUE (job_day_id, worker_id)  -- one assignment per worker per day per job
);

COMMENT ON COLUMN day_assignments.hours     IS 'Always logged regardless of worker pay_type. Used for analytics + invoice calculation.';
COMMENT ON COLUMN day_assignments.edited_at IS 'Set on any retroactive edit after initial creation.';


-- ============================================================
-- 12. EXPENSES
-- ============================================================

CREATE TABLE expenses (
    id               UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
    organization_id  UUID         NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    category         VARCHAR(50)  NOT NULL
                         CHECK (category IN ('hospital','tax','electricity','rent','fuel','transportation','other')),
    amount           DECIMAL(10,2) NOT NULL CHECK (amount >= 0),
    date             DATE          NOT NULL,
    recurring        BOOLEAN       NOT NULL DEFAULT FALSE,
    notes            TEXT,
    -- Optional links (both nullable)
    linked_worker_id UUID          REFERENCES workers(id) ON DELETE SET NULL,
    linked_job_id    UUID          REFERENCES jobs(id)    ON DELETE SET NULL,
    created_at       TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    updated_at       TIMESTAMPTZ   NOT NULL DEFAULT NOW()
);

COMMENT ON COLUMN expenses.linked_worker_id IS 'Optional. NULL = org-level overhead (rent, taxes, etc.)';
COMMENT ON COLUMN expenses.linked_job_id    IS 'Optional. Supports future job-cost/margin analysis.';


-- ============================================================
-- 13. UPCOMING BILLS
-- ============================================================

CREATE TABLE upcoming_bills (
    id                   UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
    organization_id      UUID         NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    title                VARCHAR(200) NOT NULL,
    amount               DECIMAL(10,2) NOT NULL CHECK (amount >= 0),
    due_date             DATE          NOT NULL,
    reminder_days_before INT           NOT NULL DEFAULT 7,  -- e.g. 9 → reminder fires 9 days before due
    is_paid              BOOLEAN       NOT NULL DEFAULT FALSE,
    proof_asset_id       UUID          REFERENCES assets(id) ON DELETE SET NULL,  -- attached image/receipt
    -- Optional links
    linked_worker_id     UUID          REFERENCES workers(id) ON DELETE SET NULL,
    linked_job_id        UUID          REFERENCES jobs(id)    ON DELETE SET NULL,
    -- Set once bill is paid and converted into an expense record
    converted_expense_id UUID          REFERENCES expenses(id) ON DELETE SET NULL,
    created_at           TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    updated_at           TIMESTAMPTZ   NOT NULL DEFAULT NOW()
);

COMMENT ON COLUMN upcoming_bills.reminder_days_before IS 'Reminder notification fires this many days before due_date.';
COMMENT ON COLUMN upcoming_bills.converted_expense_id IS 'Populated when a paid bill is converted/linked to an expense record.';


-- ============================================================
-- 14. INVOICES
-- ============================================================

CREATE TABLE invoices (
    id               UUID          PRIMARY KEY DEFAULT gen_random_uuid(),
    organization_id  UUID          NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    client_id        UUID          REFERENCES clients(id) ON DELETE SET NULL,
    period_start     DATE          NOT NULL,
    period_end       DATE          NOT NULL,
    total_hours      DECIMAL(8,2)  NOT NULL DEFAULT 0,
    total_amount     DECIMAL(10,2) NOT NULL DEFAULT 0,  -- gross amount owed for the period
    amount_paid      DECIMAL(10,2) NOT NULL DEFAULT 0,
    amount_owed      DECIMAL(10,2) GENERATED ALWAYS AS (total_amount - amount_paid) STORED,
    pdf_asset_id     UUID          REFERENCES assets(id) ON DELETE SET NULL,  -- generated PDF file
    sent_at          TIMESTAMPTZ,   -- when the invoice email was sent to the manager
    created_at       TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    updated_at       TIMESTAMPTZ   NOT NULL DEFAULT NOW(),

    CONSTRAINT chk_period CHECK (period_end >= period_start)
);

COMMENT ON COLUMN invoices.amount_owed  IS 'Computed: total_amount - amount_paid';
COMMENT ON COLUMN invoices.pdf_asset_id IS 'Asset record for the generated PDF; NULL until PDF is built';
COMMENT ON COLUMN invoices.sent_at      IS 'NULL until the invoice email has been dispatched to the manager';


-- Line items so the invoice breakdown is queryable (hours, rate, worker, job per row)
CREATE TABLE invoice_line_items (
    id           UUID          PRIMARY KEY DEFAULT gen_random_uuid(),
    invoice_id   UUID          NOT NULL REFERENCES invoices(id) ON DELETE CASCADE,
    worker_id    UUID          REFERENCES workers(id) ON DELETE SET NULL,
    job_id       UUID          REFERENCES jobs(id)    ON DELETE SET NULL,
    description  TEXT          NOT NULL,
    hours        DECIMAL(8,2),
    rate         DECIMAL(10,2),
    amount       DECIMAL(10,2) NOT NULL,
    created_at   TIMESTAMPTZ   NOT NULL DEFAULT NOW()
);


-- ============================================================
-- 15. BIO PAGES
-- ============================================================

CREATE TABLE bio_pages (
    id               UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    organization_id  UUID        NOT NULL UNIQUE REFERENCES organizations(id) ON DELETE CASCADE,
    slug             VARCHAR(100) NOT NULL UNIQUE,   -- public URL: mybiopage.com/<slug>
    title            VARCHAR(200),
    short_bio        TEXT,
    color_preset     VARCHAR(50),                    -- curated preset key (not user-defined hex)
    logo_asset_id    UUID        REFERENCES assets(id) ON DELETE SET NULL,
    -- Snapshot caching
    rendered_html    TEXT,                           -- static snapshot generated on every save
    last_rendered_at TIMESTAMPTZ,                    -- when the snapshot was last rebuilt
    is_published     BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON COLUMN bio_pages.slug          IS 'Public URL slug. Must be unique across the platform.';
COMMENT ON COLUMN bio_pages.rendered_html IS 'Static HTML snapshot. Regenerated on each edit and cached. Served on every public visit — no live render per visit.';
COMMENT ON COLUMN bio_pages.color_preset  IS 'Key into a curated preset list. Users pick a preset, not raw hex values.';


-- Bio page buttons (call, social links, etc.)
CREATE TABLE bio_page_buttons (
    id          UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    bio_page_id UUID        NOT NULL REFERENCES bio_pages(id) ON DELETE CASCADE,
    label       VARCHAR(100) NOT NULL,
    url         TEXT         NOT NULL,
    button_type VARCHAR(20) NOT NULL CHECK (button_type IN ('call','link','social')),
    sort_order  SMALLINT    NOT NULL DEFAULT 0,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


-- ============================================================
-- 16. REFERRALS
-- ============================================================

CREATE TABLE referral_codes (
    id               UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    organization_id  UUID        NOT NULL UNIQUE REFERENCES organizations(id) ON DELETE CASCADE,
    code             VARCHAR(50) NOT NULL UNIQUE,   -- firstname + unique number, e.g. "SARA4821"
    discount_pct     SMALLINT    NOT NULL DEFAULT 10,  -- 10% off for the new user
    created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON COLUMN referral_codes.code         IS 'Auto-generated on org creation: first name + unique number. Guaranteed unique.';
COMMENT ON COLUMN referral_codes.discount_pct IS 'One-time discount applied to the new user who signs up with this code.';


CREATE TABLE referral_uses (
    id                    UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    referral_code_id      UUID        NOT NULL REFERENCES referral_codes(id) ON DELETE RESTRICT,
    referred_organization_id UUID     NOT NULL UNIQUE REFERENCES organizations(id) ON DELETE CASCADE,
    discount_applied_pct  SMALLINT    NOT NULL,
    -- Reward for the referring org (amount/type TBD — gift card, credit, etc.)
    reward_type           VARCHAR(50),        -- 'gift_card' | 'account_credit' | NULL (not yet decided)
    reward_value          DECIMAL(10,2),
    reward_issued_at      TIMESTAMPTZ,        -- NULL until reward is sent
    used_at               TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON COLUMN referral_uses.reward_type      IS 'Reward mechanism TBD (gift card vs account credit). NULL until decided and implemented.';
COMMENT ON COLUMN referral_uses.referred_organization_id IS 'UNIQUE: a referral code can only be used once per new org.';


-- ============================================================
-- 17. INDEXES
-- ============================================================

-- Core lookup paths
CREATE INDEX idx_organizations_owner       ON organizations(owner_user_id);
CREATE INDEX idx_organizations_plan        ON organizations(plan_id);
CREATE INDEX idx_subscribed_services_org   ON subscribed_services(organization_id);
CREATE INDEX idx_subscribed_services_ext   ON subscribed_services(external_subscription_id); -- webhook lookup
CREATE INDEX idx_workers_org               ON workers(organization_id);
CREATE INDEX idx_clients_org               ON clients(organization_id);
CREATE INDEX idx_jobs_org                  ON jobs(organization_id);
CREATE INDEX idx_jobs_client               ON jobs(client_id);
CREATE INDEX idx_job_days_job              ON job_days(job_id);
CREATE INDEX idx_job_days_date             ON job_days(date);
CREATE INDEX idx_day_assignments_day       ON day_assignments(job_day_id);
CREATE INDEX idx_day_assignments_worker    ON day_assignments(worker_id);
CREATE INDEX idx_expenses_org              ON expenses(organization_id);
CREATE INDEX idx_expenses_worker           ON expenses(linked_worker_id);
CREATE INDEX idx_expenses_job              ON expenses(linked_job_id);
CREATE INDEX idx_upcoming_bills_org        ON upcoming_bills(organization_id);
CREATE INDEX idx_upcoming_bills_due        ON upcoming_bills(due_date) WHERE is_paid = FALSE; -- reminder scheduler
CREATE INDEX idx_invoices_org              ON invoices(organization_id);
CREATE INDEX idx_invoices_period           ON invoices(organization_id, period_start, period_end);
CREATE INDEX idx_invoice_line_items        ON invoice_line_items(invoice_id);
CREATE INDEX idx_bio_pages_slug            ON bio_pages(slug);
CREATE INDEX idx_assets_owner              ON assets(owner_type, owner_id);
CREATE INDEX idx_referral_codes_code       ON referral_codes(code);

-- Soft delete filters (partial indexes — only non-deleted rows)
CREATE INDEX idx_organizations_active ON organizations(id) WHERE deleted_at IS NULL;
CREATE INDEX idx_workers_active       ON workers(organization_id) WHERE deleted_at IS NULL;
CREATE INDEX idx_clients_active       ON clients(organization_id) WHERE deleted_at IS NULL;
CREATE INDEX idx_jobs_active          ON jobs(organization_id)    WHERE deleted_at IS NULL;


-- ============================================================
-- 18. UPDATED_AT TRIGGER (auto-maintain on every write)
-- ============================================================

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_updated_at_plans               BEFORE UPDATE ON plans               FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_updated_at_users               BEFORE UPDATE ON users               FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_updated_at_organizations       BEFORE UPDATE ON organizations       FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_updated_at_subscribed_services BEFORE UPDATE ON subscribed_services FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_updated_at_workers             BEFORE UPDATE ON workers             FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_updated_at_clients             BEFORE UPDATE ON clients             FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_updated_at_jobs                BEFORE UPDATE ON jobs                FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_updated_at_expenses            BEFORE UPDATE ON expenses            FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_updated_at_upcoming_bills      BEFORE UPDATE ON upcoming_bills      FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_updated_at_invoices            BEFORE UPDATE ON invoices            FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_updated_at_bio_pages           BEFORE UPDATE ON bio_pages           FOR EACH ROW EXECUTE FUNCTION set_updated_at();
